apiVersion: v1
kind: ServiceAccount
metadata:
  name: loki-s3-bucket-creator
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded,hook-failed
    # See https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html for
    # documentation about how to attach IAM permissions to service accounts
    eks.amazonaws.com/role-arn: {{ printf "arn:aws:iam::%s:role/%s" .Values.awsAccount .Values.awsRole }}